services:
  - type: web
    name: multiplayer-tictac-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
